---
title: "README"
author: "Gabriel J. Odom, PhD, ThD"
date: "August 17, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# BST 650 Course GitHub Directory
This directory is where I will store all of my course content for the fall 2018 and spring 2019 sessions of BST 650. The files and folders are

- `Literature/`: this folder is where we will store any book chapters or articles for review. In a project directory, this folder will be where you store the PDF copies of most of the sources in your background or literature review section of the report / manuscript. **For this class**, this is where I will store any **supplemental reading links or chapters**.
- `Manuscript/`: this folder will contain the drafts and supplementary materials for the project you are working on. **For this class**, this is where I will store the **lecture notes**.
- `data/`: this folder should contain all of the raw data, cleaned data, and a sub-directory for the scripts used to clean the raw data. For large projects, you may need separate directories for each of these three. **For this class**, this is where I store **example data sets**.
- `README`: this file